
replicaCount: 2
image:
  repository: my-app-image
  tag: latest
  pullPolicy: IfNotPresent

mysql:
  image: mysql:8.0
  rootPassword: rootpass
  database: mydb
  user: myuser
  password: mypass
  persistence:
    enabled: true
    size: 1Gi

service:
  type: ClusterIP
  port: 80
